# Generated by Django 3.2.6 on 2021-08-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('numberoffollowers', models.IntegerField()),
                ('numberoffollowing', models.IntegerField()),
                ('numberoftweets', models.IntegerField()),
                ('content', models.CharField(max_length=1000)),
                ('picture', models.BooleanField(default=False)),
                ('video', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
    ]
